url: https://instreha.github.io
baseurl: ""

# Site settings
title: Institut für Rehabilitation
email: praxis@institut-rehabilitation.de
description: "Das Institut für Rehabilitation besteht seit über 20 Jahren im Münchner Süden und ist durch den MVG (U3 und Bus 132 / 63) direkt mit der Innenstadt verbunden."

# Build settings
markdown: kramdown
permalink: pretty

# Therapies
collections_dir: _therapies
collections:
  - basic_therapies
  - special_therapies
  - additional_therapies
