url: https://instreha.github.io
baseurl: ""

# Site settings
title: Institut für Rehabilitation
email: praxis@institut-rehabilitation.de
description: "Das Gesundheitshaus im Münchner Süden mit ruhiger Spezialtherapie im 1.Stock, komplexer Basistherapie im EG und aktiver Trainingstherapie im UG."

# Build settings
markdown: kramdown
permalink: pretty

# Therapies
collections_dir: _therapies
collections:
  - basic_therapies
  - special_therapies
  - additional_therapies
